### ISSUE TITLE
Triple nested array breaks format

### ISSUE THREAD

**Issue by theahura** [datalanche/node-pg-format#10]
Trying to submit multiple rows into postgres where one of the columns is an array. Any nests beyond two are not handled correctly. 

For example:

`format('%L', ['a', 'b', ['c', ['d', 'e']]])`

this returns `'a','b', ('c', 'd','e')` instead of `'a','b', ('c', ('d', 'e'))`.

Is this intended? Is there a way to work around this?

**Comment by rpedela** [comment]
Sorry, that isn't supported. The easiest workaround, in general, is to break it up into multiple calls to ```format()``` and then concatenate the chunks using ```%s```. Something like this:

```js
var chunk = format('ARRAY[%L]', [ 'a', 'b', 'c' ]);
var sql = format('SELECT * FROM table WHERE c1 @> %s AND c2 = %L', chunk, 45);
```
