### ISSUE TITLE
Build query using pg-format

### ISSUE THREAD

**Issue by richlewis14** [datalanche/node-pg-format#12]
Hi

Is it possible to construct my query dynamically depending upon what parameters are passed through, so if I pass this Object to the below method

    QueryObject {
      day: 'tomorrow',
      leagueName: 'England Premier League',
      homeTeam:
        { columnOne: 'column_1',
          columnOneValue: '80' },
     awayTeam:
       { columnOne: 'column_2',
         columnOneValue: '100' } 
    }

    function buildConditions(queryObject) {
      const columns = [];
      const conditions = [];
      const values = [];

      if (typeof queryObject.homeTeam.columnOne !== 'undefined') {
        columns.push(queryObject.homeTeam.columnOne);
        conditions.push('%I = $1');
        values.push(queryObject.homeTeam.columnOneValue);
      }

      if (typeof queryObject.awayTeam.columnOne !== 'undefined') {
        columns.push(queryObject.awayTeam.columnOne);
        conditions.push('%I = $2');
        values.push(queryObject.awayTeam.columnOneValue);
      }

      return {
        where: conditions.length ? conditions.join(' AND ') : '1',
        values,
        columns,
      };
    }

It seems like I am pretty close but i get the error `Error: too few arguments`

    const conditions = buildConditions(queryObject);
    console.log(conditions);
    // { where: '%I = $1 AND %I = $2, values: [ '100', '100' ], columns: [ 'column_1', 'column_2' ] }
    const string = 'SELECT * FROM fixtures WHERE ' + conditions.where + ', ' + conditions.columns.join(', ');
    console.log(string)
    // SELECT * FROM fixtures WHERE %I = $1 AND %I = $2, column_1, column_2
    sql = format(string);

Seems I get the error when passing the string into `format`

What I don't understand at this point is if I was to construct the query as below, it works
    
    sql = format("SELECT * FROM fixtures WHERE %I = $1 AND %I = $2", queryObject.homeTeam.columnOne, queryObject.awayTeam.columnOne);

**Comment by rpedela** [comment]
In your example, ```format()``` is expecting 3 parameters: the SQL string to format and two values to replace ```%I```. That is why your first example throws an error but the second one works. In general, the number of parameters must equal the number of ```%I, %L, %s``` plus one for the SQL string.

I also see that you are building the where clause dynamically then adding it to the main query. In this case, I recommend using ```%s``` to add it to the main query and use ```format()``` when you are constructing it. Something like this:

```js
var cond1 = format('%I = $1', 'column_1');
var cond2 = format('%I = $2', 'column_2');
var conditions = [ cond1, cond2 ];
var conditions_str = conditions.join(' AND ');
var query = format('SELECT * FROM fixtures WHERE %s', conditions_str);
// SELECT * FROM fixtures WHERE column_1 = $1 AND column_2 = $2
```

For values, if you want to use ```$1, $2, etc``` then you should output the dollar sign values with ```format()``` and pass them to ```pg.query()```. Alternatively, you could use ```%L``` and the values will be escaped correctly like so:
```js
var cond1 = format('%I = %L', 'column_1', 100);
var cond2 = format('%I = %L', 'column_2', 100);
var conditions = [ cond1, cond2 ];
var conditions_str = conditions.join(' AND ');
var query = format('SELECT * FROM fixtures WHERE %s', conditions_str);
// SELECT * FROM fixtures WHERE column_1 = '100' AND column_2 = '100'
```
