### ISSUE TITLE
handle invalid Unicode code point in JSON string

### ISSUE THREAD

**Issue by brickyang** [datalanche/node-pg-format#14]
In some cases some Unicode points that are not valid in string appeared in JSON like:

```
{
    "model" : "Canon EOS 5D Mark II\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
    ....
}
```
Format this JSON directly could cause an error: `unsupported Unicode escape sequence` thrown by PostgreSQL. Otherwise, if I `stringify` it manually without the explicit cast `::jsonb`, then PostgreSQL will accept the string.

I think we could add a method after the sentence `literal = JSON.stringify(value);` to sanitize the string, like `str.replace(/\\0000/g, '')` maybe.

**Comment by rpedela** [comment]
Is your column ```json``` or ```jsonb```?

**Comment by brickyang** [comment]
@rpedela It’s JSON actually, but seems `format` add a `::jsonb` to the string via my observation.

**Comment by rpedela** [comment]
I am uncomfortable cleaning data in this library since that isn't its
purpose. Having NULL characters in a string can sometimes mean a bug in
application code and I would hate to hide such bugs. However PG does allow
NULL characters in ```json```  but not  ```jsonb``` or ```text```, and there
is a discrepancy between how this library and PG's  ```format()``` work.

We should probably fix the discrepancy, but I don't think cleaning data is
the right solution.

**Comment by brickyang** [comment]
Yes, I understand that totally.

So do you suggest cleaning the JSON data firstly then call `format` on it,
or `stringify` the JSON and clean up the string manually then `format` it?
And could you suggest some fancy libs to do those thing.

Thanks.

Ryan Pedela <notifications@github.com> 于2019年5月7日周二 上午7:43写道：

> I am uncomfortable cleaning data in this library since that isn't its
> purpose. Having NULL characters in a string can sometimes mean a bug in
> application code and I would hate to hide such bugs. However PG does allow
> NULL characters in ```json``` but not ```jsonb``` or ```text```, and there
> is a discrepancy between how this library and PG's ```format()``` work.
>
> We should probably fix the discrepancy, but I don't think cleaning data is
> the right solution.
>

**Comment by rpedela** [comment]
I recommend iterating through the JSON object and applying your regex above to any string field, then calling ```format()```. I'm sorry I don't have any recommendations for fancy cleaning libraries.
