### ISSUE TITLE
Insert multiple records in multiple tables.

### ISSUE THREAD

**Issue by hamza005** [datalanche/node-pg-format#15]
Hi, 

We can save multiple records into one table using pg-format. like
`const roleQuery = format('INSERT INTO user_roles (user_id, practice_id, role_id) VALUES %L;',[practiceArray]);`

But what if we need to add multiple records in multiple tables? I used following login but it didn't work. it's returning 'Error: too few arguments'

`const roleQuery = format( 'with new_practice as(INSERT INTO gp_checklist.user_practices (user_id, practice_id) VALUES %L)
          INSERT INTO user_roles (user_id, practice_id, role_id) VALUES %L;',
            [practiceArray, practiceRoleArray]);`

Anyone? who has done this kind of work?

**Comment by rpedela** [comment]
Can you provide a small but complete example? Then I can run it and get a better idea what the problem is.

**Comment by rpedela** [comment]
Please reopen if this is still an issue. Thanks!
