### ISSUE TITLE
How to implement "On conflict" with arrays?

### ISSUE THREAD

**Issue by kolykhalov** [datalanche/node-pg-format#16]
Greetings! :)

How can I implement  parameter from nested array in query in "on conflict" clause?

For example:

let arr = [ [1,2], [5,6] ]

pgformat('insert into sample_table (foo,bar) values %L on conflict (foo,bar) do update set foo=???, bar=??? ; ', arr)

Thanks beforehands

**Comment by rpedela** [comment]
Use the special EXCLUDED table which contains the values for the row.

```js
let arr = [ [1,2], [5,6] ]
pgformat('INSERT INTO sample_table (foo,bar) VALUES %L ON CONFLICT (foo,bar) DO UPDATE SET foo=EXCLUDED.foo, bar=EXCLUDED.bar;', arr)
```

reference: https://www.postgresql.org/docs/current/sql-insert.html
