### ISSUE TITLE
How to implement db functions into query?

### ISSUE THREAD

**Issue by kolykhalov** [datalanche/node-pg-format#17]
Hello and thank you for your work! :)

Please guide on using db functions such as newid() or now() in pg-format queries with arrays. How to call them in values in INSERT INTO?

Highly appreciated! :)
Thank you!

**Comment by kolykhalov** [comment]
Ok I got it like this (newid(), %L), [arr]

**Comment by rpedela** [comment]
Can you provide a small but complete SQL query?

**Comment by kolykhalov** [comment]
Sure. 

So the required is as following:
'Insert into some_table (id,date,col1,col2,col3...) values (newid(),now(), [array])'

where newid() - a stored function which generates new guid and now() is at it is.

Thanks :)

**Comment by rpedela** [comment]
You can call the functions like you normally would in SQL, and the array will be expanded.
```js
let myArray = [ 'a', 'b', 'c'];
let sql = format(
    'INSERT INTO some_table (id, date, col1, col2, col3) VALUES (newid(), now(), %L)',
    myArray
);
// INSERT INTO some_table (id, date, col1, col2, col3) VALUES (newid(), now(), 'a', 'b', 'c')
```

**Comment by kolykhalov** [comment]
unfortunately it expands all wrong, like this:
```
let myArray = [ 'a', 'b', 'c'];
let sql = format(
    'INSERT INTO some_table (id, date, col1, col2, col3) VALUES (newid(), now(), %L)',
    myArray
);

// INSERT INTO some_table (id,date,col1,col2,col3) VALUES (new(), now(), ('a', 'b', 'c'),('a', 'b', 'c').....('a', 'b', 'c'))
```

So it uses functions outside values and only once at the beginning and then only array values.

**Comment by rpedela** [comment]
My example uses a simple array which gives the correct SQL. Your output suggests you are giving a nested array as input which doesn't work as is. The nested array functionality is meant as a helper when you want to insert multiple rows, but its syntax isn't as flexible unfortunately. What you can do though is create a new nested array that includes ```newid()``` and ```now()``` and submit that to ```pg-format```.

```js
const format = require('pg-format');

let nested = [
    [ 'a', 'b', 'c' ],
    [ 1, 2, 3 ],
];

// 1. Append newid() and now() to each row's array.
// 2. Use %L to escape each row correctly.
// 3. Surround with parenthesis since that is required for multi-row INSERT.
let values = [];
for (let i = 0; i < nested.length; i++) {
    let row = format('(newid(), now(), %L)', nested[i]);
    values.push(row);
}

// values array already contains the correct per-row SQL so use %s to print a string.
let sql = format(
    'INSERT INTO some_table (id, date, col1, col2, col3) VALUES %s',
    values
);

console.log(sql);
// INSERT INTO some_table (id, date, col1, col2, col3) VALUES (newid(), now(), 'a','b','c'),(newid(), now(), '1','2','3')

```

**Comment by kolykhalov** [comment]
That's brilliant!!! )))

But now the output is somehow double formatted and does double quoting if array value was a string. And it is not DOUBLE QUOTES it is literary double ones of single quotes.

`// INSERT INTO some_table (id, date, col1, col2, col3) VALUES (newid(), now(), ''a'',''b'',''c''),(newid(), now(), '1','2','3')`

Am I missing something?

**Comment by rpedela** [comment]
Do your strings already contain single quotes? Are you calling ```%L``` twice on the strings? Are you using ```%s```, which doesn't quote anything, in the final step? In my example, one of the rows is all strings and they don't produce double, single quotes.

**Comment by kolykhalov** [comment]
YESSS !!! I missed %s in your example!!

Thank you so much for your help and for your work!!! :))

Highest appreciations!!!
