### ISSUE TITLE
arrays don't seem to work with updates

### ISSUE THREAD

**Issue by matthewmueller** [datalanche/node-pg-format#4]
not sure what's going on, but i can't get it to work using the example you provided.

**Comment by rpedela** [comment]
Can you show me your code? What does "don't work" mean?

**Comment by matthewmueller** [comment]
sorry that was a terrible issue, i was writing it in a hurry. here's an example:

``` js
format('UPDATE %I SET channels = (%L) WHERE team_id=%L', 'teams', ['a', 'b'], 'cool')
```

**Comment by rpedela** [comment]
What is the data type of `channels`?

**Comment by matthewmueller** [comment]
channels is the `text[]` data type

**Comment by rpedela** [comment]
This should work.

```
format('UPDATE %I SET channels = ARRAY(%L) WHERE team_id=%L', 'teams', ['a', 'b'], 'cool')
```

**Comment by rpedela** [comment]
If you get a type error then try this.

```
format('UPDATE %I SET channels = ARRAY(%L)::text[] WHERE team_id=%L', 'teams', ['a', 'b'], 'cool')
```

**Comment by matthewmueller** [comment]
Thanks for the response :-) still getting the hang of postgres. the first query worked with a slight modification:

``` diff
- ARRAY(%L)
+ ARRAY[%L]
```

Thanks for the help!
