### ISSUE TITLE
Inserting into jsonb column?

### ISSUE THREAD

**Issue by wakiem** [datalanche/node-pg-format#5]
Is there anyway to insert an object into a column of type jsonb? Because I see you do a JSON stringify now on objects.

I want to create 1 update statement that updates multiple rows and created the following:
`format("UPDATE stores AS s SET details = t.details FROM (VALUES %L) AS t(placeid, details) WHERE s.placeid = t.placeid", stores)`
Details is a column of type jsonb.
The stores array in Javascript is a double array with the first column (placeid) being a string and the second column (details) is JSON.

**Comment by rpedela** [comment]
Yes, I do it all the time. Postgres will parse the JSON string correctly. Does the resulting query work? If not, could you provide a small but complete example and we can debug together?

**Comment by wakiem** [comment]
Error I'm getting:
`Error running query { [error: column "details" is of type jsonb but expression is of type text]`

My database:

```
CREATE TABLE stores (  
    placeid text PRIMARY KEY,  
    details jsonb,  
    carriesMen boolean NOT NULL,  
    carriesWomen boolean NOT NULL,  
    created timestamp with time zone NOT NULL DEFAULT now(),  
    updated timestamp with time zone NOT NULL DEFAULT now()  
);
```

My query:

```
client.query(format("UPDATE stores AS s SET details = t.details FROM (VALUES %L) AS t(placeid, details) WHERE s.placeid = t.placeid", stores), function(err, result) {
                        if(err) {
                            console.error('Error running query', err);
                        }
                        client.end();
                    });
```

The stores object that is used (%L) is a double array like this:

```
[[placeid1,details1],
  [placeid2,details2],
  [placeid3,details3]]
```

Where placeid is a string and details is an object (JSON parsed from a string).

**Comment by rpedela** [comment]
In this case, the JSON string needs to be explicitly cast to `jsonb`. Normally that is not necessary which is why I did not implement an explicit cast. There is also the problem of two JSON types in PG. After testing, it turns out that you can explicitly cast to `json` or `jsonb` and it will work. I will update this library to explicitly cast.

**Comment by rpedela** [comment]
Please upgrade and try it and reopen if it doesn't work.

**Comment by wakiem** [comment]
It works, thanks!
