### ISSUE TITLE
Feature request: positional arguments

### ISSUE THREAD

**Issue by EdeMeijer** [datalanche/node-pg-format#6]
Hello,

I really like this project, but there's one thing I'm kind of missing; being able to specify positional arguments.

This is how I would imagine it:

```javascript
const sql = format(`
    SELECT x
    FROM table_a
    WHERE foo = %1$L

    UNION

    SELECT x
    FROM table_b
    WHERE foo = %1$L`,
    'bar'
);
```

The optional `n$` embedded in the `%L` (or other placeholders)  would refer to the nth given argument.

Is this something you could easily add? If not, I'm willing to give it a shot and send a PR, but you're more familiar with the code naturally.

Thanks!

**Comment by rpedela** [comment]
I think it could be added especially since it is a feature of [Postgres format()](https://www.postgresql.org/docs/9.3/static/functions-string.html#FUNCTIONS-STRING-FORMAT) which I try to follow as close as possible.

**Comment by rpedela** [comment]
Please open a new issue if you find any bugs.

**Comment by EdeMeijer** [comment]
Great, I'll give it a shot tomorrow. Thanks.
